<?php

declare(strict_types=1);

namespace Handlr\Generator;

/**
 * Represents a file to be generated by a Maker.
 *
 * Value object containing the target path, content, and whether
 * overwriting existing files is permitted.
 */
class GeneratedFile
{
    /**
     * @param string $path           Absolute path where the file should be written
     * @param string $content        File content to write
     * @param bool   $allowOverwrite If true, existing files can be overwritten (default: false)
     */
    public function __construct(
        public string $path,
        public string $content,
        public bool $allowOverwrite = false
    ) {}
}
